### ISSUE TITLE
bug: ghcr.io is blocked

### ISSUE THREAD

**Issue by No9** [olareg/olareg#113]
### Current Behavior

First of all thanks for creating this utility. Very useful for edge scenarios.
As per the README.md to run this as a container the command documented is:
```
docker run -p 5000:5000 \
  -v "olareg-data:/home/appuser/registry" \
  ghcr.io/olareg/olareg serve --dir /home/appuser/registry
```
However this generates the following error:
```
Error: initializing source docker://ghcr.io/olareg/olareg:latest: unable to retrieve auth token: invalid username/password: unauthorized
```

I tried creating a credential for my github account just to see if it required a github authenticated user but the issue persisted. 
```
Error: initializing source docker://ghcr.io/olareg/olareg:latest: reading manifest latest in ghcr.io/olareg/olareg: denied
```

### Expected Behavior

The docker command should run sucessfully without authentication

### Version

```text
Latest as of 2024-06-09
```

### Environment
Linux RHEL x86_64

**Comment by sudo-bmitch** [comment]
Thank you for catching that! I've made the package public. Let me know if you have any further issues.
