### ISSUE TITLE
[Issue] `olareg help serve` does not mention the "shared" store option

### ISSUE THREAD

**Issue by mohag** [olareg/olareg#156]
### Current Behavior

```
$ olareg help serve
Run a registry server

Usage:
  olareg serve [flags]

Examples:

<snip>

Flags:
<snip>
      --store-type string          storage type (dir, mem) (default "dir")
<snip>
```

### Expected Behavior

The shared store type should also show.

### Steps To Reproduce

In a container from ghcr.io/olareg/olareg:edge-alpine:
Run `olareg help serve` and check the output.

### Version

```text
 $ olareg version
VCSTag:     (devel)
VCSRef:     003b719af399682673c301cec902726a84bb4f2e-dirty
VCSCommit:  003b719af399682673c301cec902726a84bb4f2e
VCSState:   dirty
VCSDate:    2024-12-29T15:42:28Z
Platform:   linux/amd64
GoVer:      go1.23.4
GoCompiler: gc
```

### Environment

- Running as binary or container: container
- Host platform: Linux
- Other tools / container runtimes: docker

### Anything else

I'm currently considering olareg for a containerised registry mirror. The default store seems to be usable to load in the contents of the tarballs that come out of `ctr image export` which is awesome. (I was looking at the shared store to reduce duplication (I think I saw it in the code) when I noticed this)

**Comment by mohag** [comment]
Ok, that store might not be working:
```
~ $ docker push localhost/olareg/olareg:edge
The push refers to repository [localhost/olareg/olareg]
6dfc3bb3f798: Retrying in 4 seconds
c08bf7a96dd8: Retrying in 4 seconds
8fe07296a23e: Retrying in 4 seconds
4adbcf9b435e: Retrying in 4 seconds
^C
~ $ docker logs olareg
time=2024-12-31T14:52:57.429Z level=ERROR msg="ServeHTTP called without a backend store"
time=2024-12-31T14:52:57.430Z level=ERROR msg="ServeHTTP called without a backend store"
time=2024-12-31T14:52:57.430Z level=ERROR msg="ServeHTTP called without a backend store"
time=2024-12-31T14:52:57.431Z level=ERROR msg="ServeHTTP called without a backend store"
time=2024-12-31T14:52:57.431Z level=ERROR msg="ServeHTTP called without a backend store"
time=2024-12-31T14:52:57.432Z level=ERROR msg="ServeHTTP called without a backend store"
```

[This seems to be the only reference to it](https://github.com/olareg/olareg/blob/003b719af399682673c301cec902726a84bb4f2e/config/config.go#L25)

So I'm guessing it is not implemented yet... (I can probably run fdupes and hardlink duplicate blobs)

**Comment by mohag** [comment]
I'm guessing that a shared store should be quite simple: Move the blobs directory to the root of the store directory instead of under the individual repository

**Comment by sudo-bmitch** [comment]
> So I'm guessing it is not implemented yet... (I can probably run fdupes and hardlink duplicate blobs)

Correct, not implemented yet. Hard links are a consideration for how to implement it, but that may limit the underlying filesystem.

> I'm guessing that a shared store should be quite simple: Move the blobs directory to the root of the store directory instead of under the individual repository

That would be part of the solution, but individual blob directories are still needed per repo to follow the OCI Layout specification. If a user later changes the root to be a sub-directory or parent directory, that would cause things to break. GC would need to be aware of the parent blobs folder and all child repositories, even those created outside of olareg. And the repo listing API (`_catalog`) would likely get supported in the process.

**Comment by mohag** [comment]
Some other notes:
I was looking at the registry specification and thinking that I'll probably write a script to take OCI image exports and populate them in a web server's document root to make a basic registry (for mirroring images). (It seems that pull conformance should be possible that way, but discovery conformance would need some code (the tag listing request needs the ability to give a subset of results)
When looking at the conformance info, I came across olareg amongst the conformant implementations, which seems like an easier solution.

(sym)linking a shared blobs into each repo's directory might still be conformant? (when using "shared") It would have all blobs present though, not just that repo... (when data is being pushed, it is easy, if data is manually being copied in, it would need quite a bit of documentation)

Hard links would be awesome, but yes, it would likely limit the file system options (symlinks as well, to a lesser degree). The count of the link count (with hard-links) might help for garbage collection... (For my use case (where olareg would run read-only) creating the hard links externally would work though, so I'll probably do that)

**Comment by sudo-bmitch** [comment]
For creating a static data source, you can first generate all the registry content (copy everything into a writable olareg instance, or using `regctl image copy $src ocidir://$dir:$tag`). Then rearrange the blobs by putting them in a single folder and symlink to that as you suggest. When running the registry, use read only mode with the GC disabled. That would mean blobs can be pulled from any repo, which some might consider a security issue, but that's unlikely to be a problem in this scenario.
